// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyRestApi.DbServices;

#nullable disable

namespace MyRestApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230920104157_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyRestApi.Models.PersonModel", b =>
                {
                    b.Property<Guid>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonId");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            PersonId = new Guid("ec12c381-338b-44fb-95ec-7129fa8303d2"),
                            Age = 25,
                            Email = "kevin@gmail.com",
                            Name = "Kevin",
                            PhotoUrl = "https://images.pexels.com/photos/2380794/pexels-photo-2380794.jpeg?auto=compress&cs=tinysrgb&w=600"
                        },
                        new
                        {
                            PersonId = new Guid("7e72f589-3ca8-47d7-909e-4e89166c8793"),
                            Age = 26,
                            Email = "marta@gmail.com",
                            Name = "Marta",
                            PhotoUrl = "https://images.pexels.com/photos/3586798/pexels-photo-3586798.jpeg?auto=compress&cs=tinysrgb&w=600"
                        },
                        new
                        {
                            PersonId = new Guid("ef47e070-32f1-4488-8711-2b11ff1a45c9"),
                            Age = 22,
                            Email = "nicole@gmail.com",
                            Name = "Nicole",
                            PhotoUrl = "https://images.pexels.com/photos/1994818/pexels-photo-1994818.jpeg?auto=compress&cs=tinysrgb&w=600"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
